# Generated by Django 5.2.4 on 2026-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_data', models.JSONField()),
                ('discovered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
