# Generated by Django 5.2.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                ("db_name", models.CharField(max_length=255)),
                ("db_user", models.CharField(max_length=255)),
                ("password_ciphertext", models.TextField()),
                ("schema_text", models.TextField(blank=True, default="")),
                ("discovered_tables", models.JSONField(blank=True, default=list)),
                ("allowed_tables", models.JSONField(blank=True, default=list)),
                ("industry", models.CharField(blank=True, default="", max_length=120)),
                ("business", models.TextField(blank=True, default="")),
                ("keeps", models.JSONField(blank=True, default=list)),
                ("is_readonly_role", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workspaceconnection",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_workspace_connection_per_user"
            ),
        ),
    ]
