# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_workspaceconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceconnection",
            name="host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workspaceconnection",
            name="db_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workspaceconnection",
            name="db_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workspaceconnection",
            name="password_ciphertext",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workspaceconnection",
            name="discovered_columns",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workspaceconnection",
            name="allowed_columns",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
