# Generated by Django 6.1.1 on 2026-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_engine_and_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedqueryexample',
            options={'ordering': ['-created_at'], 'verbose_name': 'verified query example', 'verbose_name_plural': 'verified query examples'},
        ),
        migrations.AlterModelOptions(
            name='workspaceconnection',
            options={'verbose_name': 'workspace connection', 'verbose_name_plural': 'workspace connections'},
        ),
        migrations.RenameIndex(
            model_name='verifiedqueryexample',
            new_name='connections_workspa_7eb5c2_idx',
            old_name='connections_workspa_7a1c2e_idx',
        ),
    ]
