# Generated by Django 5.2.4 on 2026-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_chat_conver_updated_1f6ffe_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_id'], name='chat_conver_user_id_54eba5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant_id'], name='chat_conver_tenant__3af0ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_id', 'tenant_id'), name='unique_conversation_user_tenant'),
        ),
    ]
