# Generated by Django 5.2.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_tenant_id_conversation_user_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_conversation_user_tenant",
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="chat_conver_user_id_54eba5_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="user_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["user"], name="chat_conver_user_id_a8bae4_idx"),
        ),
    ]
