# Generated by Django 5.2.4 on 2026-09-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_workspace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_user_id_54eba5_idx',
            old_name='chat_conver_user_id_a8bae4_idx',
        ),
    ]
