# Generated by Django 6.1.1 on 2026-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_organization_product_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'API access request', 'verbose_name_plural': 'API access requests'},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
    ]
