# Validates SQL
# Repair SQL / execute SQL

# agent/nodes/sql_validator.py

from typing import Any

from connections.services.sql_validation import ReadOnlySQLExecutor

from ..state import QueryMindState
from chat.api.chat_service import SQLFallbackInterceptor

ALLOWED_TENANT_TABLES = {
    "users",
    "password_reset_tokens",
    "sessions",
    "cache",
    "cache_locks",
}


def sql_validator(state: QueryMindState) -> dict[str, Any]:
    """
    Validate the SQL generated by the SQL generator node.

    This node is responsible only for:
    - reading SQL from state
    - calling the SQL validation service
    - storing the validation result
    - updating execution state

    This node does NOT:
    - generate SQL
    - execute SQL
    - repair SQL
    - analyze database errors
    - call Ollama
    - decide the next graph node
    """

    try:
        is_fallback, fallback_reason = SQLFallbackInterceptor.analyze_query(
            sql=state.sql, allowed_tables=ALLOWED_TENANT_TABLES
        )

    except Exception as exc:

        # ========================================================
        # 4. Validation failed
        # ========================================================

        return {
            "validation_result": {
                "valid": is_fallback,
                "error": str(exc),
                "fallback_reason": str(fallback_reason),
            },
            "database_error": None,
            "current_node": "sql_validator",
            "status": "running",
        }

    return {
        "validation_result": {
            "valid": bool(is_fallback),
            "fallback_reason": (str(fallback_reason) if fallback_reason else None),
        },
        "database_error": None,
        "current_node": "sql_validator",
        "status": "running",
    }
