# Validates SQL
# Repair SQL / execute SQL

# agent/nodes/sql_validator.py

from typing import Any

from connections.services.sql_validation import ReadOnlySQLExecutor

from ..state import QueryMindState


def sql_validator(state: QueryMindState) -> dict[str, Any]:
    """
    Validate the SQL generated by the SQL generator node.

    This node is responsible only for:
    - reading SQL from state
    - calling the SQL validation service
    - storing the validation result
    - updating execution state

    This node does NOT:
    - generate SQL
    - execute SQL
    - repair SQL
    - analyze database errors
    - call Ollama
    - decide the next graph node
    """

    sql = (state.sql or "").strip()

    # ============================================================
    # 1. Make sure SQL exists
    # ============================================================

    if not sql:
        return {
            "validation_result": {
                "valid": False,
                "error": "No SQL query was generated.",
            },
            "current_node": "sql_validator",
            "status": "running",
        }

    # ============================================================
    # 2. Validate SQL
    # ============================================================

    executor = ReadOnlySQLExecutor(
        database="client",
    )

    try:
        expression = executor.validate(sql)

        # ========================================================
        # 3. Validation succeeded
        # ========================================================

        normalized_sql = expression.sql(
            dialect="postgres",
        )

        return {
            "sql": normalized_sql,
            "validation_result": {
                "valid": True,
                "error": None,
            },
            "database_error": None,
            "current_node": "sql_validator",
            "status": "running",
        }

    except Exception as exc:

        # ========================================================
        # 4. Validation failed
        # ========================================================

        return {
            "validation_result": {
                "valid": False,
                "error": str(exc),
            },
            "database_error": None,
            "current_node": "sql_validator",
            "status": "running",
        }
